# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference

version: 2.1
# deleted trigger and configuration
jobs: 
  test: # your job name
    macos:
      xcode: 15.3 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme WikiTopicSearch

  build:
    macos:
      xcode: 15.3 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/WikiTopicSearch.app
      #- store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
       #   path: app.zip
        #  destination: app
          
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
